version: '3'
services:
  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: xml
    networks:
      - static-network


  auth-service:
    image: auth-service
    build:
      context: ./services/Auth-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  cart-service:
    image: cart-service
    build:
      context: ./services/Cart-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server


  vehicle-service:
    image: vehicle-service
    build:
      context: ./services/Vehicle-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  message-service:
    image: message-service
    build:
      context: ./services/Message-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  grading-service:
    image: grading-service
    build:
      context: ./services/Grading-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  gateway:
    image: gateway
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8080:8080"
    networks:
      - static-network
    depends_on:
      - consul-server

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - static-network
volumes:
  sample_db:


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16