server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehicle
          uri: lb://vehicle
          predicates:
            - Path=/vehicle/**
          filters:
            - RewritePath=/vehicle/(?<path>.*), /$\{path}
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/(?<path>.*), /$\{path}
        - id: message
          uri: lb://message
          predicates:
            - Path=/message/**
          filters:
            - RewritePath=/message/(?<path>.*), /$\{path}
        - id: grading
          uri: lb://grading
          predicates:
            - Path=/grading/**
          filters:
            - RewritePath=/grading/(?<path>.*), /$\{path}
            
