server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer/(?<path>.*), /$\{path}
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/(?<path>.*), /$\{path}